CREATE DATABASE verzel;

CREATE TABLE IF NOT EXISTS carros(
  id SERIAL PRIMARY KEY,
  nome TEXT NOT NULL,
  marca TEXT NOT NULL,
  modelo TEXT NOT NULL,
  foto TEXT NOT NULL,
  preco INTEGER,
);

CREATE TABLE IF NOT EXISTS usuarios(
  id SERIAL PRIMARY KEY,
  nome TEXT NOT NULL UNIQUE,
  senha TEXT NOT NULL,
  admin BOOLEAN NOT NULL DEFAULT FALSE
);